<?php

function siteprocessor_topblock_block_info(){
  $blocks=array(
    'topblock' =>array(
      'info' => t('Top block'),
      'cache' => DRUPAL_NO_CACHE, 
    ),
  );
  return $blocks;
}

function siteprocessor_topblock_block_view($delta){
  $block=array();
  switch ($delta){
    case 'topblock':
    $block['subject'] ='';
    //$block['#theme'] ='';
    //$block['content'] ='TOP BLOCK CONTENT';
    if ($image_fid = variable_get('siteprocessor_topblock_image_fid', FALSE)) {
      $image = file_load($image_fid);
      $block['content']=theme('image_style',array('style_name'=>'toplogo_image','path'=>$image->uri));
    }
    else {
      $block['content']='';
    }
    break;
  }
  return $block;
}


function siteprocessor_topblock_init(){
  if ($image_fid = variable_get('siteprocessor_topblock_background_image_fid', FALSE)) {
    $image = file_load($image_fid);
    $image_url=file_create_url($image->uri);
    drupal_add_css("
body{
  background-image:url($image_url);
  background-position:top center;
  background-repeat:no-repeat;         
}
    ",'inline');
//$block['content']=theme('image_style',array('style_name'=>'toplogo_image','path'=>$image->uri));
  }  
}

function siteprocessor_topblock_permission() {
  return array(
    'administer site processor top block'=>array(
      'title'=>t('administer site processor top block'),
      'description'=>t('administer site processor top block'),
    ),
  );
}

function siteprocessor_topblock_menu() {
  $items['admin/media/siteprocessor_topblock'] = array(
    'title' => 'Topblock admin',
    'description' => 'Topblock admin',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('siteprocessor_topblock_settings_form'),
    'access callback' => 'user_access',
    'access arguments' => array('administer siteprocessor top block '),
    'file' => 'siteprocessor_topblock.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


function siteprocessor_topblock_settings_form_submit($form, &$form_state) {
  if ($form_state['values']['siteprocessor_topblock_image_fid'] != 0) {
    $file = file_load($form_state['values']['siteprocessor_topblock_image_fid']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    file_usage_add($file, 'siteprocessor_topblock', 'topblock_image', 1);
    variable_set('siteprocessor_topblock_image_fid', $file->fid);
    drupal_set_message(t('The image @image_name was uploaded and saved with an ID of @fid', array('@image_name' => $file->filename, '@fid' => $file->fid)));
  }
  elseif ($form_state['values']['siteprocessor_topblock_image_fid'] == 0) {
    $fid = variable_get('siteprocessor_topblock_image_fid', FALSE);
    $file = $fid ? file_load($fid) : FALSE;
    if ($file) {
      file_usage_delete($file, 'siteprocessor_topblock', 'topblock_image', 1);
      file_delete($file);
    }
    variable_set('siteprocessor_topblock_image_fid', FALSE);
    drupal_set_message(t('The image @image_name was removed.', array('@image_name' => $file->filename)));
  }

  if ($form_state['values']['siteprocessor_topblock_background_image_fid'] != 0) {
    $file = file_load($form_state['values']['siteprocessor_topblock_background_image_fid']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    file_usage_add($file, 'siteprocessor_topblock', 'topblock_background_image', 1);
    variable_set('siteprocessor_topblock_background_image_fid', $file->fid);
    drupal_set_message(t('The background image @image_name was uploaded and saved with an ID of @fid', array('@image_name' => $file->filename, '@fid' => $file->fid)));
  }
  elseif ($form_state['values']['siteprocessor_topblock_background_image_fid'] == 0) {
    $fid = variable_get('siteprocessor_topblock_background_image_fid', FALSE);
    $file = $fid ? file_load($fid) : FALSE;
    if ($file) {
      file_usage_delete($file, 'siteprocessor_topblock', 'topblock_background_image', 1);
      file_delete($file);
    }
    variable_set('siteprocessor_topblock_background_image_fid', FALSE);
    drupal_set_message(t('The background image @image_name was removed.', array('@image_name' => $file->filename)));
  }
  
}


/*function siteprocessor_topblock_settings_form_validate($form, &$form_state) {
  if (!isset($form_state['values']['siteprocessor_topblock_image_fid']) || !is_numeric($form_state['values']['siteprocessor_topblock_image_fid'])) {
    form_set_error('siteprocessor_topblock_image_fid', t('Please select an image to upload.'));
  }
}*/