<?php
/**
 * @file
 * Code for the siteprocessor_base feature.
 */

include_once('siteprocessor_base.features.inc');

/**
 * Implements hook_block_info().
 */
function siteprocessor_base_block_info(){
  $blocks=array(
    'frontpage' =>array(
      'info' => t('Front page button'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function siteprocessor_base_block_view($delta){
  $block=array();
  switch ($delta){
    case 'frontpage':
    $block['subject'] ='Home button';
    $block['content']='<a class="frontpage-link" href="/">'.t('Front page').'</a>';
    break;
  }
  return $block;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Hide views exposed filters for taxonomy terms
 * if no terms available.
 */
function siteprocessor_base_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form['field_event_category_tid']['#size'] == 0) {
    unset($form['#info']['filter-field_event_category_tid']) ;
  }
  if ($form['field_event_target_tid']['#size'] == 0) {
    unset($form['#info']['filter-field_event_target_tid']) ;
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function siteprocessor_base_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['large_item'] = array(
    'label' => t('Large item'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['list_item'] = array(
    'label' => t('List item'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['imagetile_item'] = array(
    'label' => t('Image tile item'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['carousel_item'] = array(
    'label' => t('Carousel item'),
    'custom settings' => TRUE,
  );
}

