<?php
/**
 * @file
 * Code for the siteprocessor_event feature.
 */

include_once('siteprocessor_event.features.inc');

/**
 * Implements hook_date_format_types().
 *
 * Create a few custom date formatters.
 */
function siteprocessor_event_date_format_types() {
  return array(
    'event_short' => t('Short event'),
    'event_long' => t('Long event'),
  );
}

/**
 * Implements hook_date_formats().
 *
 * Create a few custom date formats
 */
function siteprocessor_event_date_formats() {
  return array(
    array(
    'type' => 'event_short',
    'format' => 'D, d. M. Y',
    ),
    array(
    'type' => 'event_long',
    'format' => 'D, j. M. Y G:i',
    ),
  );
}

function siteprocessor_preprocess_calendar_datebox(&$vars) {
  drupal_add_js(drupal_get_path('module', 'siteprocessor_event') .'/calendar_filter.js', 'file');
  global $base_url;
  $vars['url'] = $base_url . "/" .arg(0). "/" . $vars['date'];
  $vars['link'] = l($vars['day'], $vars['url']);
}
