<?php
/**
 * @file
 * Code for the siteprocessor_article feature.
 */

include_once('siteprocessor_article.features.inc');

/**
 * Implements hook_date_format_types().
 *
 * Create a few custom date formatters.
 */
function siteprocessor_article_date_format_types() {
  return array(
    'article_short' => t('Short article'),
    'article_long' => t('Long article'),
  );
}

/**
 * Implements hook_date_formats().
 *
 * Create a few custom date formats
 */
function siteprocessor_article_date_formats() {
  return array(
    array(
    'type' => 'article_short',
    'format' => 'j/m G:i',
    ),
    array(
    'type' => 'article_long',
    'format' => 'D, j. M. Y G:i"',
    ),
  );
}
